name: Website Health Check

on:
  # schedule:
  #   - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  check-site:
    runs-on: ubuntu-latest

    steps:
      - name: Check https://www.perfectcorp.com/business
        run: |
          URL="https://www.perfectcorp.com/business"
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" $URL)
          echo "Status code: $STATUS"
          
          if [ "$STATUS" -ne 200 ]; then
            echo "❌ Website is DOWN! Status: $STATUS"
            exit 1
          else
            echo "✅ Website is UP. Status: $STATUS"
          fi
